services:
  iterative_code.docker_jobs.service.docker:
    public: true
    class: IterativeCode\DockerJobsBundle\Service\DockerService
    arguments:
      - '@service_container'
      - '%docker_jobs.docker.unix_socket_path%'
      - '%docker_jobs.docker.api_base_uri%'

  iterative_code.docker_jobs.manager.job:
    public: true
    class: IterativeCode\DockerJobsBundle\Manager\JobManager
    arguments:
      - '@service_container'

  iterative_code.docker_jobs.twig.extension.job:
    class: IterativeCode\DockerJobsBundle\Twig\JobExtension
    arguments:
      - '@service_container'
    tags:
      - { name: twig.extension }
